Lesson 1
idoleg/react-03.03 pull request #13
Opened 2020-03-06 02:23 UTC by Roguey-84

2020-03-09 12:47 UTC, idoleg requested changes
У вас красивый дизайн
Ваша проблема заключается в том, что по нажатию на кнопку вы не вызываете preventDefault() и у вас обновляется страница
Жду исправление и смержу

2020-03-09 12:47 UTC, idoleg commented on SvetlanaMaltseva/src/components/messages/Form.js
> +    e.preventDefault;
Вы забыли тут круглые скобки
Это вызов функции

2020-03-09 13:43 UTC, Roguey-84 commented on SvetlanaMaltseva/src/components/messages/Form.js
> +    e.preventDefault;
Спасибо, я исправила, видимо, поторопилась.

2020-03-09 13:48 UTC, Roguey-84 commented
Исправления добавила, теперь все работает, спасибо.

2020-03-12 17:38 UTC, idoleg approved these changes
Отлично

2020-03-12 17:38 UTC, merged