lesson1
idoleg/react-03.03 pull request #3
Opened 2020-03-03 21:44 UTC by senior012

2020-03-04 08:38 UTC, idoleg requested changes
жду, пока лишние файлы будут удалены

2020-03-04 08:38 UTC, idoleg commented on .idea/deployment.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Просьба убрать из PR файлы, не относящиеся к уроку

2020-03-04 08:38 UTC, idoleg commented on Konstantin_Grigoryevyh/app_src/index.html
> +<script src="app/build/app.js"></script>
эту строчку код вебпак добавляет автоматически

2020-03-04 09:01 UTC, senior012 commented
> жду, пока лишние файлы будут удалены
да, я вчера недоделанный пул сделал, добью еще )

2020-03-04 21:54 UTC, senior012 commented
готово

2020-03-09 12:08 UTC, idoleg approved these changes
Отлично

2020-03-09 12:08 UTC, idoleg commented on Konstantin_Grigoryevyh/components/index.js
> +        const array = [...this.state.messages, message];
плохое название переменной

2020-03-09 12:09 UTC, merged