Anastasia Pakhomova HW after Lesson-3
idoleg/react-03.03 pull request #75
Opened 2020-03-20 12:24 UTC by Anastasia-Pakhomova

2020-03-21 09:07 UTC, idoleg requested changes
Исправить

2020-03-21 09:07 UTC, idoleg commented on AnastasiaPakhomova/src/components/ChatForm/ChatForm.jsx
> +			document.getElementById('text-field').focus()
это не правильно (здесь и далее)
вы не должны обращаться к getElementById, это ломает всю независимость вашего реакт коспонента, используйте рефы

2020-03-21 10:28 UTC, Anastasia-Pakhomova reviewed
Исправила.

2020-04-08 08:17 UTC, idoleg approved these changes
Вот теперь все хорошо

2020-04-08 08:17 UTC, merged